name: step_create_python_environment
inputs:
  pipFilePath:
    required: false
    default: "src/promptflow/dev_requirements.txt"
    type: string
  pythonVersion:
    required: false
    default: "3.9"
    type: string
runs:
  using: composite
  steps:
  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.pythonVersion }}
  - run: |
      python -m pip install --upgrade pip
      pip install -r ${{ inputs.pipFilePath }}
      pip freeze
      sudo cp src/promptflow/az.py /usr/bin/az
      sudo chmod +x /usr/bin/az
      pip install requests
    shell: pwsh
